#!/usr/bin/env ruby

require 'class_indexer'

# Find ruby files
files  = Dir.glob('**/*.rb')
output = {}

# Parse every file we found
files.each do |input_file|
  output[input_file] = ClassIndexer::process_file(input_file)
end

# Output json (pretty format)

if ARGV[0] == '-p'
  jj output
else
  j output
end
